### ISSUE TITLE
Upgrade package aws-xray-sdk-core

### ISSUE THREAD

**Issue by matthewbpt** [serverless-seoul/dynamorm#14]
Could the version of the `aws-xray-sdk-core` package be updated? The version you currently have has needlessly limited the node engine to <= node 8, but if you bump it to at least `2.2.0` this limitation will be dropped (see https://github.com/aws/aws-xray-sdk-node/commit/0e3e291825eaaac95fe6868a12c143d09ec7570b)

**Comment by matthewbpt** [comment]
I created a PR that does the above here https://github.com/serverless-seoul/dynamorm/pull/15

**Comment by breath103** [comment]
closing since it's resolved
