### ISSUE TITLE
Documentation: primaryKey hash

### ISSUE THREAD

**Issue by ostmond** [serverless-seoul/dynamorm#19]
In the document on https://serverless-seoul.github.io/dynamorm/docs/quick-start it hashes the primaryKey to number:
`public static readonly primaryKey: Query.HashPrimaryKey<BlogPost, number>; `

But by searching it calls with string:
`let post = await BlogPost.primaryKey.get("first-blog-post");`

It gave me error notification in VS-Code. I suppose it should be hashed to string:
`public static readonly primaryKey: Query.HashPrimaryKey<BlogPost, string>; `

Shouldn't it?

**Comment by breath103** [comment]
Hi, yes it is. since "id" is primaryKey. will fix the docs soon, or you can commit change to PR

**Comment by breath103** [comment]
fixed, thanks for the report
