### ISSUE TITLE
Documentation: Does DynamoORM work with private members?

### ISSUE THREAD

**Issue by jwvanhollebeke** [serverless-seoul/dynamorm#38]
## Question

Does DynamoORM support decorators on private members?

## Scenario

We have an entity with member of type optional Array. We have additional methods on this entity that can perform filter/map operations on the array. We don't want callers to swap the array of an entity with another array, instead we prefer that they only work through the interface we provide. 

Therefore, we would like to make the array member `private`, and this seems to work, but I couldn't find anything in the documentation indicating that this is a supported use case. Instead, I see in the [model guide](https://serverless-seoul.github.io/dynamorm/docs/model) that all members are explicitly marked `public`.

## Example

```
@Decorator.Attribute({ name: 'media' })
private _myArray?: MyInterface[];

/**
 * Get all array items
 */
get media(): MediaInfo[] {
  // lazy initialize the array
  if (!this._myArray) {
    this._myArray = [];

  }

  return this._myArray;
}

/**
 * Count of items with certain characteristics in the array
 */
get myFavoriteItemsCount(): number {
  return this.myArray.filter(m => m.category === Category.MyFavorite).length;
}
```

Thanks so much for considering my question, we love DynamoORM!

**Comment by breath103** [comment]
Yes this is completely valid usage. i personally use this pattern a lot too
such as when the PK is complex object, and has to be serialize when we put it in DynamoDB but should be parsed into object when we read it
in which case, you should override getter and setter, keeping the actual attribute private

**Comment by jwvanhollebeke** [comment]
Awesome thanks for confirming, @breath103. I was hoping you would say that.
