### ISSUE TITLE
Expressions missing

### ISSUE THREAD

**Issue by rogueturnip** [serverless-seoul/dynamorm#9]
Glad to see this being forked to keep things moving forward.

I did  notice when I converted over that a number of attributes are now missing.  AttributeExists and Equals being two..

These use to be in query/expressions/conditions/operators.ts.

**Comment by mooyoul** [comment]
Hello there. I'm the original author of Condition Expression feature.
I've checked forked source code and can confirm some source codes weren't synced up-to-date.
Currently i'm working on this and it will be fixed soon. Thanks for your reporting!

**Comment by rogueturnip** [comment]
Great!  This one feature is holding back my conversion.

**Comment by rogueturnip** [comment]
Wanted to find out the plan on this one since it holds me back doing the conversion.

**Comment by breath103** [comment]
@mooyoul can you check on this.

**Comment by mooyoul** [comment]
Issue was outdated base branch - We merged all upstream changes and released [v2.11.0](https://github.com/serverless-seoul/dynamorm/releases/tag/v2.11.0). Try it out - `npm install @serverless-seoul/dynamorm@latest --save`
